// Psychiatrists and Demo Data for MindCare Center
const PSYCHIATRISTS_DATA = [
  {
    id: 'patrick-jane',
    name: 'Patrick Jane',
    isPremium: true,
    premiumBadge: 'Premium Psychiatrist',
    specialization: 'Psychological Assessment & Behavioral Analysis',
    qualification: 'Senior Consultant in Behavioral Analysis & Counseling',
    experience: '15+ Years Clinical & Analytical Experience',
    rating: 5.0,
    reviews: 248,
    fee: '$250',
    timings: 'Tue - Sat (10:30 AM - 5:30 PM)',
    availableSlots: ['10:30 AM', '01:00 PM', '02:30 PM', '04:00 PM', '05:30 PM'],
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=800',
    bio: 'Experienced in psychological assessment, counseling, and behavioral analysis.',
    location: 'Executive Wellness Suite 501, MindCare Pavilion',
    fullBio: 'Patrick Jane brings exceptional observational acuity to psychological assessment, personal counseling, and behavioral analysis. With a distinct focus on unlocking underlying emotional blocks and decoding interpersonal dynamics, his sessions provide deep clarity, calm perspective, and transformative behavioral guidance.'
  },
  {
    id: 'dr-sarah-wilson',
    name: 'Dr. Sarah Wilson, MD',
    specialization: 'Adult Psychiatry & Mood Disorders',
    qualification: 'MD, Board Certified in Adult Psychiatry',
    experience: '14 Years Experience',
    rating: 4.9,
    reviews: 128,
    fee: '$180',
    timings: 'Mon - Fri (9:00 AM - 5:00 PM)',
    availableSlots: ['09:00 AM', '10:30 AM', '01:00 PM', '02:30 PM', '04:00 PM'],
    photo: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=600',
    bio: 'Specializes in clinical depression, bipolar disorders, and medical management with a compassionate, evidence-based approach.',
    location: 'Suite 301, Medical Arts Building',
    fullBio: 'Dr. Sarah Wilson has over 14 years of hospital and clinical experience. She specializes in mood disorders, medical pharmacotherapy, and integrative lifestyle support for adult patients.'
  },
  {
    id: 'dr-david-chen',
    name: 'Dr. David Chen, MD',
    specialization: 'Anxiety, Panic & Psychotherapy',
    qualification: 'MD, FAPA (Fellow of American Psychiatric Association)',
    experience: '16 Years Experience',
    rating: 4.9,
    reviews: 142,
    fee: '$175',
    timings: 'Mon, Wed, Thu (8:30 AM - 4:30 PM)',
    availableSlots: ['08:30 AM', '10:00 AM', '11:30 AM', '02:00 PM', '03:30 PM'],
    photo: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=600',
    bio: 'Expert in panic attacks, social anxiety, and integrating medical pharmacology with cognitive therapy strategies.',
    location: 'Suite 204, Wellness Wing',
    fullBio: 'Dr. David Chen balances neurochemistry and psychotherapy. He works with adults navigating high-pressure careers, generalized anxiety, and panic disorder.'
  },
  {
    id: 'dr-elena-rostova',
    name: 'Dr. Elena Rostova, MD',
    specialization: 'Child & Adolescent Mental Health',
    qualification: 'MD, Certified in Child & Adolescent Psychiatry',
    experience: '11 Years Experience',
    rating: 5.0,
    reviews: 160,
    fee: '$195',
    timings: 'Tue - Sat (10:00 AM - 6:00 PM)',
    availableSlots: ['10:00 AM', '11:30 AM', '01:30 PM', '03:00 PM', '04:30 PM'],
    photo: 'https://images.unsplash.com/photo-1594824813627-8025287ec224?auto=format&fit=crop&q=80&w=600',
    bio: 'Dedicated to supporting adolescents, students, and children facing behavioral shifts, ADHD, and school-related stress.',
    location: 'Suite 105, Family Clinic Center',
    fullBio: 'Dr. Elena Rostova creates an encouraging, safe space for youth and families. She is passionate about early emotional intervention and positive developmental outcomes.'
  },
  {
    id: 'dr-marcus-vance',
    name: 'Dr. Marcus Vance, MD, PhD',
    specialization: 'Neuropsychiatry & Cognitive Health',
    qualification: 'MD, PhD in Cognitive Neuroscience',
    experience: '18 Years Experience',
    rating: 4.8,
    reviews: 95,
    fee: '$210',
    timings: 'Tue, Thu, Fri (10:00 AM - 4:00 PM)',
    availableSlots: ['10:00 AM', '11:30 AM', '02:00 PM', '03:30 PM'],
    photo: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=600',
    bio: 'Focuses on the intersection of neurological function and psychiatric symptoms, memory wellness, and complex diagnoses.',
    location: 'Suite 410, Neuro Science Pavilion',
    fullBio: 'Dr. Marcus Vance is a dual-trained physician-scientist focusing on organic brain conditions, executive function, and memory optimization.'
  },
  {
    id: 'dr-amara-okafor',
    name: 'Dr. Amara Okafor, MD',
    specialization: 'Trauma & PTSD Recovery',
    qualification: 'MD, Certified Trauma Specialist',
    experience: '12 Years Experience',
    rating: 4.9,
    reviews: 114,
    fee: '$190',
    timings: 'Mon - Thu (10:00 AM - 5:30 PM)',
    availableSlots: ['10:00 AM', '11:30 AM', '01:30 PM', '03:00 PM', '04:30 PM'],
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=600',
    bio: 'Provides gentle, trauma-informed care for patients navigating grief, high-stress occupations, and post-traumatic recovery.',
    location: 'Suite 302, Medical Arts Building',
    fullBio: 'Dr. Amara Okafor offers patient-centered autonomic stabilization, PTSD recovery protocols, and compassionate care for survivors of acute life stressors.'
  },
  {
    id: 'dr-lucas-romero',
    name: 'Dr. Lucas Romero, MD',
    specialization: 'Sleep Psychiatry & Lifestyle Wellness',
    qualification: 'MD, Certified in Sleep Medicine',
    experience: '13 Years Experience',
    rating: 4.8,
    reviews: 89,
    fee: '$170',
    timings: 'Mon, Wed, Fri (9:00 AM - 4:30 PM)',
    availableSlots: ['09:00 AM', '10:30 AM', '01:00 PM', '02:30 PM', '04:00 PM'],
    photo: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=600',
    bio: 'Helps patients resolve chronic insomnia, sleep anxiety, circadian rhythm disruption, and daytime exhaustion.',
    location: 'Suite 208, Wellness Wing',
    fullBio: 'Dr. Lucas Romero is an expert in circadian health, cognitive behavioral therapy for insomnia (CBT-I), and restorative psychiatric sleep protocols.'
  }
];

const INITIAL_APPOINTMENTS = [
  {
    id: 'APT-1082',
    doctorId: 'dr-sarah-wilson',
    doctorName: 'Dr. Sarah Wilson, MD',
    doctorSpecialty: 'Adult Psychiatry & Mood Disorders',
    doctorPhoto: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=600',
    date: '2026-10-05',
    time: '10:30 AM',
    patientName: 'Alex Morgan',
    patientEmail: 'alex.morgan@example.com',
    patientPhone: '+1 (555) 234-5678',
    consultationType: 'Online Video',
    reason: 'Routine follow-up on mood stabilization and prescription check',
    status: 'Upcoming'
  },
  {
    id: 'APT-0941',
    doctorId: 'dr-david-chen',
    doctorName: 'Dr. David Chen, MD',
    doctorSpecialty: 'Anxiety, Panic & Psychotherapy',
    doctorPhoto: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=600',
    date: '2026-08-14',
    time: '02:00 PM',
    patientName: 'Alex Morgan',
    patientEmail: 'alex.morgan@example.com',
    patientPhone: '+1 (555) 234-5678',
    consultationType: 'In-Person Clinic',
    reason: 'Initial consultation regarding stress management and occasional panic',
    status: 'Completed'
  }
];
